//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilORama.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool reuseFiles {
            get {
                return ((bool)(this["reuseFiles"]));
            }
            set {
                this["reuseFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileAudioLast {
            get {
                return ((string)(this["fileAudioLast"]));
            }
            set {
                this["fileAudioLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseLOR {
            get {
                return ((bool)(this["UseLOR"]));
            }
            set {
                this["UseLOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UsexLights {
            get {
                return ((bool)(this["UsexLights"]));
            }
            set {
                this["UsexLights"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autoLaunch {
            get {
                return ((bool)(this["autoLaunch"]));
            }
            set {
                this["autoLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool xTimesIndiv {
            get {
                return ((bool)(this["xTimesIndiv"]));
            }
            set {
                this["xTimesIndiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Bar and Beat Tracker")]
        public string methodBarsBeats {
            get {
                return ((string)(this["methodBarsBeats"]));
            }
            set {
                this["methodBarsBeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool doChromagram {
            get {
                return ((bool)(this["doChromagram"]));
            }
            set {
                this["doChromagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int timeSignature {
            get {
                return ((int)(this["timeSignature"]));
            }
            set {
                this["timeSignature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int startBeat {
            get {
                return ((int)(this["startBeat"]));
            }
            set {
                this["startBeat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string detectBars {
            get {
                return ((string)(this["detectBars"]));
            }
            set {
                this["detectBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool whiteBarsBeats {
            get {
                return ((bool)(this["whiteBarsBeats"]));
            }
            set {
                this["whiteBarsBeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string fileTimingsLast {
            get {
                return ((string)(this["fileTimingsLast"]));
            }
            set {
                this["fileTimingsLast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X:\\2025\\xLights\\Wizlights\\Timings")]
        public string LastxLightsTimingsSavePath {
            get {
                return ((string)(this["LastxLightsTimingsSavePath"]));
            }
            set {
                this["LastxLightsTimingsSavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string annotatorProgram {
            get {
                return ((string)(this["annotatorProgram"]));
            }
            set {
                this["annotatorProgram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public byte saveFormat {
            get {
                return ((byte)(this["saveFormat"]));
            }
            set {
                this["saveFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doBars {
            get {
                return ((bool)(this["doBars"]));
            }
            set {
                this["doBars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doBeatsFull {
            get {
                return ((bool)(this["doBeatsFull"]));
            }
            set {
                this["doBeatsFull"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doBeatsHalf {
            get {
                return ((bool)(this["doBeatsHalf"]));
            }
            set {
                this["doBeatsHalf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool doBeatsThird {
            get {
                return ((bool)(this["doBeatsThird"]));
            }
            set {
                this["doBeatsThird"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doBeatsQuarter {
            get {
                return ((bool)(this["doBeatsQuarter"]));
            }
            set {
                this["doBeatsQuarter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25ms 40fps")]
        public string alignBarBeats {
            get {
                return ((string)(this["alignBarBeats"]));
            }
            set {
                this["alignBarBeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string labelBarBeats {
            get {
                return ((string)(this["labelBarBeats"]));
            }
            set {
                this["labelBarBeats"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Note Onset Detector")]
        public string methodOnsets {
            get {
                return ((string)(this["methodOnsets"]));
            }
            set {
                this["methodOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int sensitivityOnsets {
            get {
                return ((int)(this["sensitivityOnsets"]));
            }
            set {
                this["sensitivityOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doOnsets {
            get {
                return ((bool)(this["doOnsets"]));
            }
            set {
                this["doOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Note Names")]
        public string labelOnsets {
            get {
                return ((string)(this["labelOnsets"]));
            }
            set {
                this["labelOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25ms 40fps")]
        public string alignOnsets {
            get {
                return ((string)(this["alignOnsets"]));
            }
            set {
                this["alignOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doTranscribe {
            get {
                return ((bool)(this["doTranscribe"]));
            }
            set {
                this["doTranscribe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Note Names")]
        public string labelTranscribe {
            get {
                return ((string)(this["labelTranscribe"]));
            }
            set {
                this["labelTranscribe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25ms 40fps")]
        public string alignTranscribe {
            get {
                return ((string)(this["alignTranscribe"]));
            }
            set {
                this["alignTranscribe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Key Detector")]
        public string methodPitchKey {
            get {
                return ((string)(this["methodPitchKey"]));
            }
            set {
                this["methodPitchKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doPitchKey {
            get {
                return ((bool)(this["doPitchKey"]));
            }
            set {
                this["doPitchKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Key Names")]
        public string labelPitchKey {
            get {
                return ((string)(this["labelPitchKey"]));
            }
            set {
                this["labelPitchKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Note Onset Detector")]
        public string methodTempo {
            get {
                return ((string)(this["methodTempo"]));
            }
            set {
                this["methodTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doTempo {
            get {
                return ((bool)(this["doTempo"]));
            }
            set {
                this["doTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string labelTempo {
            get {
                return ((string)(this["labelTempo"]));
            }
            set {
                this["labelTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool doSegments {
            get {
                return ((bool)(this["doSegments"]));
            }
            set {
                this["doSegments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full Beats / Quarter Notes")]
        public string alignSegments {
            get {
                return ((string)(this["alignSegments"]));
            }
            set {
                this["alignSegments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Segmenter")]
        public string methodSegments {
            get {
                return ((string)(this["methodSegments"]));
            }
            set {
                this["methodSegments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25ms 40fps")]
        public string alignChromagram {
            get {
                return ((string)(this["alignChromagram"]));
            }
            set {
                this["alignChromagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Polyphonic Transcription")]
        public string methodChromagram {
            get {
                return ((string)(this["methodChromagram"]));
            }
            set {
                this["methodChromagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Note Names")]
        public string labelChromagram {
            get {
                return ((string)(this["labelChromagram"]));
            }
            set {
                this["labelChromagram"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool doChords {
            get {
                return ((bool)(this["doChords"]));
            }
            set {
                this["doChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Full Beats / Quarter Notes")]
        public string alignChords {
            get {
                return ((string)(this["alignChords"]));
            }
            set {
                this["alignChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Polyphonic Transcription")]
        public string methodChords {
            get {
                return ((string)(this["methodChords"]));
            }
            set {
                this["methodChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string detectOnsets {
            get {
                return ((string)(this["detectOnsets"]));
            }
            set {
                this["detectOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool whiteOnsets {
            get {
                return ((bool)(this["whiteOnsets"]));
            }
            set {
                this["whiteOnsets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("441")]
        public string stepSize {
            get {
                return ((string)(this["stepSize"]));
            }
            set {
                this["stepSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ramps {
            get {
                return ((bool)(this["Ramps"]));
            }
            set {
                this["Ramps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Queen Mary Polyphonic Transcription")]
        public string methodTranscribe {
            get {
                return ((string)(this["methodTranscribe"]));
            }
            set {
                this["methodTranscribe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25ms 40fps")]
        public string alignPitchKey {
            get {
                return ((string)(this["alignPitchKey"]));
            }
            set {
                this["alignPitchKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25ms 40fps")]
        public string alignTempo {
            get {
                return ((string)(this["alignTempo"]));
            }
            set {
                this["alignTempo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string labelSegments {
            get {
                return ((string)(this["labelSegments"]));
            }
            set {
                this["labelSegments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string labelChords {
            get {
                return ((string)(this["labelChords"]));
            }
            set {
                this["labelChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUfilesAudio0 {
            get {
                return ((string)(this["MRUfilesAudio0"]));
            }
            set {
                this["MRUfilesAudio0"] = value;
            }
        }
    }
}
