//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilORama4 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtilORama4.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups can only be mapped to other groups if they have the same number of regular channels, RGB channels, and subgroups in the same order..
        /// </summary>
        internal static string MSG_GroupMatch {
            get {
                return ResourceManager.GetString("MSG_GroupMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups can only be mapped to other groups, and only if they have the same number of regular channels and RGB channels in the same order..
        /// </summary>
        internal static string MSG_GroupToGroup {
            get {
                return ResourceManager.GetString("MSG_GroupToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular channels can only be mapped to other regular channels..
        /// </summary>
        internal static string MSG_MapRegularToRegular {
            get {
                return ResourceManager.GetString("MSG_MapRegularToRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGB channels can only be mapped to other RGB channels..
        /// </summary>
        internal static string MSG_MapRGBtoRGB {
            get {
                return ResourceManager.GetString("MSG_MapRGBtoRGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Old Channel not mapped to New LORChannel4..
        /// </summary>
        internal static string MSG_NoMap {
            get {
                return ResourceManager.GetString("MSG_NoMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Old Channel mapped to New LORChannel4, but not vise-versa..
        /// </summary>
        internal static string MSG_OneWay {
            get {
                return ResourceManager.GetString("MSG_OneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected new group already has an old group mapped to it..
        /// </summary>
        internal static string MSG_OnlyOneGroupToNew {
            get {
                return ResourceManager.GetString("MSG_OnlyOneGroupToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected new channel already has an old channel mapped to it..
        /// </summary>
        internal static string MSG_OnlyOneOldToNew {
            get {
                return ResourceManager.GetString("MSG_OnlyOneOldToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks can only be mapped to other tracks, and ONLY if they have the exact same number of regular channels, RGB channels, and channel groups, and in the exact same order..
        /// </summary>
        internal static string MSG_Tracks {
            get {
                return ResourceManager.GetString("MSG_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LORChannel4 Configs (*.lcc)|*.lcc|Musical Sequences (*.lms)|*.lms|Animated Sequences (*.las)|*.las.
        /// </summary>
        internal static string OpenDialogFilter_Master {
            get {
                return ResourceManager.GetString("OpenDialogFilter_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Sequences (*.lms)|*.lms|Animated Sequences (*.las)|*.las.
        /// </summary>
        internal static string OpenDialogFilter_Source {
            get {
                return ResourceManager.GetString("OpenDialogFilter_Source", resourceCulture);
            }
        }
    }
}
